# Generated by Django 5.1.7 on 2025-04-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_account_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('Pickles', 'Pickles'), ('Sweets', 'Sweets'), ('Snacks', 'Snacks')], max_length=20)),
                ('image', models.ImageField(upload_to='product_images/')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('pickle_type', models.CharField(blank=True, choices=[('Veg', 'Vegetarian'), ('Non-Veg', 'Non-Vegetarian')], max_length=10, null=True)),
                ('sweet_type', models.CharField(blank=True, choices=[('Sugar', 'With Sugar'), ('No-Sugar', 'Sugar-Free')], max_length=10, null=True)),
            ],
        ),
    ]
