# Generated by Django 5.1.7 on 2025-04-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pickle_type',
            field=models.CharField(blank=True, choices=[('veg', 'Vegetarian'), ('nonveg', 'Non-Vegetarian')], max_length=20, null=True),
        ),
    ]
