# Generated by Django 5.1.7 on 2025-04-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address_line',
        ),
        migrations.RemoveField(
            model_name='address',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='address',
            name='landmark',
        ),
        migrations.RemoveField(
            model_name='address',
            name='pincode',
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.CharField(default='India', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='postal_code',
            field=models.CharField(default='000000', max_length=20),
        ),
        migrations.AddField(
            model_name='address',
            name='street',
            field=models.CharField(default='Default Street', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=100),
        ),
    ]
